sources:
  - Panamera.glyphs
familyName: "Panamera"
buildWebfont: true
buildVariable: false
axisOrder:
  - wght
stat:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 220
    - name: Light
      value: 300
    - name: Regular
      value: 400
    - name: Medium
      value: 500
    - name: Bold
      value: 790
    - name: Heavy
      value: 800

